# Changes here will be overwritten by Copier
_commit: cf81ff6
_src_path: gh:34j/pypackage-template
add_me_as_contributor: false
cli_name: vr180-convert
copyright_year: '2024'
documentation: true
email: 34j.95a2p@simplelogin.com
full_name: 34j
github_username: 34j
has_cli: true
initial_commit: true
open_source_license: MIT
open_with_vscode: true
package_name: vr180_convert
project_name: VR180 image converter
project_short_description: Simple VR180 image converter
project_slug: vr180-convert
run_poetry_install: true
setup_github: true
setup_pre_commit: true
setup_venv: true
venv_version: '3.11'

