# Changes here will be overwritten by Copier
_commit: a3d26ee
_src_path: gh:34j/pypackage-template
cli_name: vr180-convert
copyright_year: '2024'
documentation: true
email: 34j.95a2p@simplelogin.com
full_name: 34j
github_username: 34j
has_cli: true
initial_commit: false
is_django_package: false
open_source_license: MIT
open_with_editor: false
package_name: vr180_convert
project_name: VR180 image converter
project_short_description: Simple VR180 image converter
project_slug: vr180-convert
run_uv_sync: true
setup_github: false
setup_pre_commit: false

