# Changes here will be overwritten by Copier
_commit: cf81ff6
_src_path: gh:34j/pypackage-template
add_me_as_contributor: false
cli_name: vr180-convert
copyright_year: '2024'
documentation: true
email: 34j.95a2p@simplelogin.com
full_name: 34j
github_username: 34j
has_cli: true
initial_commit: false
open_source_license: MIT
open_with_vscode: false
package_name: vr180_convert
project_name: VR180 image converter
project_short_description: Simple VR180 image converter
project_slug: vr180-convert
run_poetry_install: false
setup_github: false
setup_pre_commit: false
setup_venv: false
venv_version: '3.11'

